name = "wiki-sts2-app"
pages_build_output_dir = "dist"
compatibility_date = "2025-10-08"

[[r2_buckets]]
binding = "WIKI_MEDIA"
bucket_name = "wiki-sts2"

[[analytics_engine_datasets]]
binding = "WIKI_ANALYTICS"
dataset = "wiki_sts2_events"
